apiVersion: v1
kind: ConfigMap
metadata:
  name: env-var-default
  namespace: default
data:
  ENVIRONMENT: DEV
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-var-front-backend
  namespace: default
data:
# Define to use recaptcha
  RECAPTCHA_SITEKEY: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-var-aws
  namespace: default
data:
# Define these variables to save raw messages in S3
  AWS_SECRET_ACCESS_KEY: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_DEFAULT_REGION: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-var-postgres
  namespace: default
data:
  DB_HOST: postgres
  DB_NAME: rolaguard_local
  DB_PORT: "5432"
  DB_USERNAME: postgres
  DB_PASSWORD: post_gres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-var-rabbitmq
  namespace: default
data:
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_DEFAULT_USER: user
  RABBITMQ_DEFAULT_PASS: user
  RABBITMQ_QUEUE: data_collectors_test_events
  RABBITMQ_EXCHANGE: data_collectors_events
  RABBITMQ_POOL_SIZE: "8"
  RABBITMQ_POOL_RECYCLE: "600"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-var-backend
  namespace: default
data:
  JWT_SECRET_KEY: "your_jwt_secret"
  SECRET: "your_secret"
  MASTER_KEY: "df_a-ZnsRjabCdO1pRq8fVs0dp6kbfKrVLCjiaBotbc="
# Define to use recaptcha
  RECAPTCHA_SECRET_KEY: ""
  ASSIGN_COLLECTOR_TO_USER_ENABLED: "False"
  SEND_SMS: "False"
  SEND_EMAILS: "False"
  SMTP_HOST: "your_smtp_host.com"
  SMTP_PORT: "587"
  SMTP_USERNAME: "your_smtp_user"
  SMTP_PASSWORD: "your_smtp_password"
  SMTP_SENDER: "donotreply@your_host.com" 
  SMTP_SENDER_NAME: "RoLaGuard Community"
  SMTP_MAX_SEND_MAIL_ATTEMPTS: "5"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-var-frontend
  namespace: default
data:
  REACT_APP_API_HOST: http://localhost.rolaguard:30003/api/v1.0/
  REACT_APP_WS_HOST: http://localhost.rolaguard:30003/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-var-data-collectors
  namespace: default
data:
  API_HOST: backend:5000
  API_USER: user.orchestrator
  API_PASSWORD: rolaguard_password